import { SystemData, ImportBatch, SalesRecord, SalespersonConfig } from '../types';

export const INITIAL_SYSTEM_DATA: SystemData = (() => {
  const batchId = 'sample_batch_2026_07';
  const sampleBatch: ImportBatch = {
    id: batchId,
    month: '2026-07',
    fileName: '2026年7月销售记录示例.xlsx',
    uploadedAt: new Date().toISOString(),
    recordCount: 12,
    totalAmount: 168000,
  };

  const sampleRecords: SalesRecord[] = [
    {
      id: `${batchId}_1`,
      batchId,
      month: '2026-07',
      date: '2026/7/1',
      incomeName: '张小明',
      project: '少儿美术',
      type: '新',
      amount: 3800,
      salesperson: '王顾问',
      teacher: '李老师',
      notes: '标准年卡课程',
    },
    {
      id: `${batchId}_2`,
      batchId,
      month: '2026-07',
      date: '2026/7/2',
      incomeName: '李思思',
      project: '硬笔书法',
      type: '新',
      amount: 4500,
      salesperson: '王顾问',
      teacher: '陈老师',
      notes: '暑期班+硬笔套装',
    },
    {
      id: `${batchId}_3`,
      batchId,
      month: '2026-07',
      date: '2026/7/3',
      incomeName: '赵雷',
      project: '少儿英语',
      type: '续',
      amount: 8000,
      salesperson: '王顾问',
      teacher: '张老师',
      notes: '续费两年套餐',
    },
    {
      id: `${batchId}_4`,
      batchId,
      month: '2026-07',
      date: '2026/7/5',
      incomeName: '孙悟空',
      project: '夏令营集训',
      type: '集训',
      amount: 6800,
      salesperson: '王顾问',
      teacher: '李老师',
      notes: '7天闭环特训',
    },
    {
      id: `${batchId}_5`,
      batchId,
      month: '2026-07',
      date: '2026/7/6',
      incomeName: '钱七',
      project: '少儿美术',
      type: '新',
      amount: 12000,
      salesperson: '王顾问',
      teacher: '李老师',
      notes: '三年VIP班',
    },
    {
      id: `${batchId}_6`,
      batchId,
      month: '2026-07',
      date: '2026/7/8',
      incomeName: '周八',
      project: '少儿英语',
      type: '新',
      amount: 15000,
      salesperson: '王顾问',
      teacher: '张老师',
      notes: '新报高端班',
    },
    {
      id: `${batchId}_7`,
      batchId,
      month: '2026-07',
      date: '2026/7/10',
      incomeName: '吴九',
      project: '硬笔书法',
      type: '续',
      amount: 45000,
      salesperson: '王顾问',
      teacher: '陈老师',
      notes: '老学员高额续费',
    },
    {
      id: `${batchId}_8`,
      batchId,
      month: '2026-07',
      date: '2026/7/12',
      incomeName: '郑十',
      project: '少儿美术',
      type: '续',
      amount: 10000,
      salesperson: '王顾问',
      teacher: '',
      notes: '无指定老师续费',
    },
    {
      id: `${batchId}_9`,
      batchId,
      month: '2026-07',
      date: '2026/7/15',
      incomeName: '林一',
      project: '少儿英语',
      type: '新',
      amount: 22000,
      salesperson: '张顾问',
      teacher: '张老师',
      notes: '非自主招生顾问招收',
    },
    {
      id: `${batchId}_10`,
      batchId,
      month: '2026-07',
      date: '2026/7/18',
      incomeName: '徐二',
      project: '夏令营集训',
      type: '集训',
      amount: 5000,
      salesperson: '张顾问',
      teacher: '陈老师',
      notes: '集训班学员',
    },
    {
      id: `${batchId}_11`,
      batchId,
      month: '2026-07',
      date: '2026/7/20',
      incomeName: '胡三',
      project: '少儿美术',
      type: '续',
      amount: 16000,
      salesperson: '张顾问',
      teacher: '李老师',
      notes: '续费大单',
    },
    {
      id: `${batchId}_12`,
      batchId,
      month: '2026-07',
      date: '2026/7/25',
      incomeName: '高四',
      project: '硬笔书法',
      type: '新',
      amount: 20000,
      salesperson: '张顾问',
      teacher: '陈老师',
      notes: '新报名书法全能班',
    },
  ];

  const sampleConfigs: Record<string, SalespersonConfig> = {
    王顾问: {
      salesperson: '王顾问',
      role: '普通课程顾问',
      otherAmountByMonth: { '2026-07': 500 },
    },
    张顾问: {
      salesperson: '张顾问',
      role: '非自主招生课程顾问',
      otherAmountByMonth: { '2026-07': 0 },
    },
  };

  return {
    batches: [sampleBatch],
    records: sampleRecords,
    configs: sampleConfigs,
  };
})();
